version: "3.1"

services:
  admin-web:
    build: 
      context: ./client
      dockerfile : Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - compose-networks

  admin-server:
    build: 
      context: ./server
      dockerfile : Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/admin
    networks:
      - compose-networks

networks:
  compose-networks:
